# The name of this site
# This text displays in the back-office and
# can be used in templates through the site.name global variable
name: "Art des Nations"

# An array of domain aliases for the site
# This option is for sites on multi-site engines
# domains: [www.example.com, example.com]

# An array of locales (languages) the site is available in
# The locale listed first is the site's default locale
# Locales are specified using ISO language codes
# Possible locales include: en, de, fr, pl, pt-BR, it, nl, nb, es, ru, et, ja, zh-CN
locales: [en, fr, ru, zh-CN]

# The site's timezone
# This converts the server's time to the site's time zone in templates
# The TimeZone class from Rail's ActiveSupport is used to interpret the string
# Sample timezone strings: Tokyo, Beijing, Moscow, Cairo, Paris, Pacific Time (US & Canada)
timezone: Paris

# For SEO purposes, sites may wish to add a relevant string to the <title> tag
# And include <meta type="keywords"> and <meta type="description">
# For this purpose you can set values for these variables here
# They can be accessed in templates through the site.seo_title, site.meta_keywords, and site.meta_description variables
seo_title: "Art des Nations"
  # fr: "Centre pour l'amitié franco-russe et franco-chinoise"
  # ru: "Центр Франко-русский и франко-китайские дружеские"
  # zh-CN: "中心法俄和法 - 中国友谊"
meta_keywords:
  en: "Franco-Russian friendship, Franco-Chinese friendship"
  fr: "Amitié franco-russe, amitié franco-chinoise"
meta_description: "Website of Art des Nations"
  # fr: "Site internet de l'amiété franco-russe et franco-chinoise"
  # ru: "Центр веб-сайт для дружбы Франко - русской и Франко - китайский"
  # zh-CN: "中心网站为法俄友谊和法国 - 中国"
